version: 0.0
os: linux

files:
  - source: /
    destination: /
    
permissions:
  - object: /
    owner: ubuntu
    pattern: "**"
    group: ubuntu
    mode: 644
hooks:
  AfterInstall:
    # location은 프로젝트의 root경로를 기준
    - location: deploy.sh
      timeout: 60
      runas: root
